apiVersion: v1
kind: Service
metadata:
  name: retriever
  namespace: rag
  labels:
    app: retriever
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: /actuator/prometheus
spec:
  selector:
    app: retriever
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retriever
  namespace: rag
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retriever
  template:
    metadata:
      labels:
        app: retriever
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: /actuator/prometheus
    spec:
      serviceAccountName: retriever
      initContainers:
        - name: otel-agent-downloader
          image: busybox:1.36
          command:
            - sh
            - -c
            - >
              wget -q -O /otel/javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.5.0/opentelemetry-javaagent.jar
          volumeMounts:
            - name: otel-agent
              mountPath: /otel
      containers:
        - name: retriever
          image: europe-north1-docker.pkg.dev/mohamed-playground/rag-demo/rag-retriever:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: retriever-config
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.observability.svc.cluster.local:4317
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/javaagent.jar"
          volumeMounts:
            - name: otel-agent
              mountPath: /otel
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
      volumes:
        - name: otel-agent
          emptyDir: {}
